server:
  port: 0

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery:
          timeout:
            ms: 120000
        linger:
          ms: 0
        request:
          timeout:
            ms: 30000
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5
        enable:
          idempotence: true
      transaction-id-prefix: transfer-service-${random.value}-
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        transaction: DEBUG
#        kafka:
#          transaction:
#            KafkaTransactionManager: DEBUG
#        orm:
#          jpa:
#            JpaTransactionManager: DEBUG
      apache:
        kafka:
          clients:
            producer:
              internals:
                TransactionManager: DEBUG

withdraw-money-topic: withdraw-money-topic
deposit-money-topic: deposit-money-topic


