server:
  port: 0

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: amount-deposit-event
      properties:
        spring:
          json:
            trusted:
              packages: com.appsdeveloperblog.*
      isolation-level: read_committed